version: "3.1"

services:

  mysql:
    image: mysql:5.7.18
    container_name: mysql
    # Set max_allowed_packet to 512M for provisioning
    command: --max-allowed-packet=512M --performance-schema=FALSE --transaction-isolation=READ-COMMITTED --init-connect='SET collation_connection=utf8_bin' --init-connect='SET NAMES utf8;' --character-set-server=utf8 --collation-server=utf8_bin --lower-case-table-names=2 --max-connections=500
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
     - "3306:3306"
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql

  # http://localhost:3307/
  # username / pass: root / root

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '3307:80'
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data: